// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: task.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskService_CheckTask_FullMethodName              = "/task.TaskService/CheckTask"
	TaskService_UpdateTask_FullMethodName             = "/task.TaskService/UpdateTask"
	TaskService_NewTask_FullMethodName                = "/task.TaskService/NewTask"
	TaskService_SaveTaskResult_FullMethodName         = "/task.TaskService/SaveTaskResult"
	TaskService_SaveVulResult_FullMethodName          = "/task.TaskService/SaveVulResult"
	TaskService_KeepAlive_FullMethodName              = "/task.TaskService/KeepAlive"
	TaskService_GetWorkerConfig_FullMethodName        = "/task.TaskService/GetWorkerConfig"
	TaskService_RequestResource_FullMethodName        = "/task.TaskService/RequestResource"
	TaskService_GetTemplatesByTags_FullMethodName     = "/task.TaskService/GetTemplatesByTags"
	TaskService_GetCustomFingerprints_FullMethodName  = "/task.TaskService/GetCustomFingerprints"
	TaskService_ValidateFingerprint_FullMethodName    = "/task.TaskService/ValidateFingerprint"
	TaskService_ValidatePoc_FullMethodName            = "/task.TaskService/ValidatePoc"
	TaskService_BatchValidatePoc_FullMethodName       = "/task.TaskService/BatchValidatePoc"
	TaskService_GetPocValidationResult_FullMethodName = "/task.TaskService/GetPocValidationResult"
	TaskService_GetPocById_FullMethodName             = "/task.TaskService/GetPocById"
	TaskService_GetTemplatesByIds_FullMethodName      = "/task.TaskService/GetTemplatesByIds"
	TaskService_GetHttpServiceMappings_FullMethodName = "/task.TaskService/GetHttpServiceMappings"
	TaskService_GetSubfinderProviders_FullMethodName  = "/task.TaskService/GetSubfinderProviders"
)

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 任务服务
type TaskServiceClient interface {
	// 检查任务状态
	CheckTask(ctx context.Context, in *CheckTaskReq, opts ...grpc.CallOption) (*CheckTaskResp, error)
	// 更新任务状态
	UpdateTask(ctx context.Context, in *UpdateTaskReq, opts ...grpc.CallOption) (*UpdateTaskResp, error)
	// 创建执行器任务
	NewTask(ctx context.Context, in *NewTaskReq, opts ...grpc.CallOption) (*NewTaskResp, error)
	// 保存任务结果
	SaveTaskResult(ctx context.Context, in *SaveTaskResultReq, opts ...grpc.CallOption) (*SaveTaskResultResp, error)
	// 保存漏洞结果
	SaveVulResult(ctx context.Context, in *SaveVulResultReq, opts ...grpc.CallOption) (*SaveVulResultResp, error)
	// Worker心跳
	KeepAlive(ctx context.Context, in *KeepAliveReq, opts ...grpc.CallOption) (*KeepAliveResp, error)
	// 获取Worker配置
	GetWorkerConfig(ctx context.Context, in *GetWorkerConfigReq, opts ...grpc.CallOption) (*GetWorkerConfigResp, error)
	// 请求资源文件
	RequestResource(ctx context.Context, in *RequestResourceReq, opts ...grpc.CallOption) (*RequestResourceResp, error)
	// 根据标签获取模板
	GetTemplatesByTags(ctx context.Context, in *GetTemplatesByTagsReq, opts ...grpc.CallOption) (*GetTemplatesByTagsResp, error)
	// 获取自定义指纹
	GetCustomFingerprints(ctx context.Context, in *GetCustomFingerprintsReq, opts ...grpc.CallOption) (*GetCustomFingerprintsResp, error)
	// 验证指纹匹配
	ValidateFingerprint(ctx context.Context, in *ValidateFingerprintReq, opts ...grpc.CallOption) (*ValidateFingerprintResp, error)
	// POC验证
	ValidatePoc(ctx context.Context, in *ValidatePocReq, opts ...grpc.CallOption) (*ValidatePocResp, error)
	// 批量POC验证
	BatchValidatePoc(ctx context.Context, in *BatchValidatePocReq, opts ...grpc.CallOption) (*BatchValidatePocResp, error)
	// 查询POC验证结果
	GetPocValidationResult(ctx context.Context, in *GetPocValidationResultReq, opts ...grpc.CallOption) (*GetPocValidationResultResp, error)
	// 根据ID获取POC内容
	GetPocById(ctx context.Context, in *GetPocByIdReq, opts ...grpc.CallOption) (*GetPocByIdResp, error)
	// 根据ID列表批量获取模板内容
	GetTemplatesByIds(ctx context.Context, in *GetTemplatesByIdsReq, opts ...grpc.CallOption) (*GetTemplatesByIdsResp, error)
	// 获取HTTP服务映射
	GetHttpServiceMappings(ctx context.Context, in *GetHttpServiceMappingsReq, opts ...grpc.CallOption) (*GetHttpServiceMappingsResp, error)
	// 获取Subfinder数据源配置
	GetSubfinderProviders(ctx context.Context, in *GetSubfinderProvidersReq, opts ...grpc.CallOption) (*GetSubfinderProvidersResp, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) CheckTask(ctx context.Context, in *CheckTaskReq, opts ...grpc.CallOption) (*CheckTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckTaskResp)
	err := c.cc.Invoke(ctx, TaskService_CheckTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) UpdateTask(ctx context.Context, in *UpdateTaskReq, opts ...grpc.CallOption) (*UpdateTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTaskResp)
	err := c.cc.Invoke(ctx, TaskService_UpdateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) NewTask(ctx context.Context, in *NewTaskReq, opts ...grpc.CallOption) (*NewTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewTaskResp)
	err := c.cc.Invoke(ctx, TaskService_NewTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) SaveTaskResult(ctx context.Context, in *SaveTaskResultReq, opts ...grpc.CallOption) (*SaveTaskResultResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveTaskResultResp)
	err := c.cc.Invoke(ctx, TaskService_SaveTaskResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) SaveVulResult(ctx context.Context, in *SaveVulResultReq, opts ...grpc.CallOption) (*SaveVulResultResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveVulResultResp)
	err := c.cc.Invoke(ctx, TaskService_SaveVulResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) KeepAlive(ctx context.Context, in *KeepAliveReq, opts ...grpc.CallOption) (*KeepAliveResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeepAliveResp)
	err := c.cc.Invoke(ctx, TaskService_KeepAlive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetWorkerConfig(ctx context.Context, in *GetWorkerConfigReq, opts ...grpc.CallOption) (*GetWorkerConfigResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkerConfigResp)
	err := c.cc.Invoke(ctx, TaskService_GetWorkerConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) RequestResource(ctx context.Context, in *RequestResourceReq, opts ...grpc.CallOption) (*RequestResourceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestResourceResp)
	err := c.cc.Invoke(ctx, TaskService_RequestResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTemplatesByTags(ctx context.Context, in *GetTemplatesByTagsReq, opts ...grpc.CallOption) (*GetTemplatesByTagsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTemplatesByTagsResp)
	err := c.cc.Invoke(ctx, TaskService_GetTemplatesByTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetCustomFingerprints(ctx context.Context, in *GetCustomFingerprintsReq, opts ...grpc.CallOption) (*GetCustomFingerprintsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomFingerprintsResp)
	err := c.cc.Invoke(ctx, TaskService_GetCustomFingerprints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ValidateFingerprint(ctx context.Context, in *ValidateFingerprintReq, opts ...grpc.CallOption) (*ValidateFingerprintResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateFingerprintResp)
	err := c.cc.Invoke(ctx, TaskService_ValidateFingerprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ValidatePoc(ctx context.Context, in *ValidatePocReq, opts ...grpc.CallOption) (*ValidatePocResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidatePocResp)
	err := c.cc.Invoke(ctx, TaskService_ValidatePoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) BatchValidatePoc(ctx context.Context, in *BatchValidatePocReq, opts ...grpc.CallOption) (*BatchValidatePocResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchValidatePocResp)
	err := c.cc.Invoke(ctx, TaskService_BatchValidatePoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetPocValidationResult(ctx context.Context, in *GetPocValidationResultReq, opts ...grpc.CallOption) (*GetPocValidationResultResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPocValidationResultResp)
	err := c.cc.Invoke(ctx, TaskService_GetPocValidationResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetPocById(ctx context.Context, in *GetPocByIdReq, opts ...grpc.CallOption) (*GetPocByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPocByIdResp)
	err := c.cc.Invoke(ctx, TaskService_GetPocById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTemplatesByIds(ctx context.Context, in *GetTemplatesByIdsReq, opts ...grpc.CallOption) (*GetTemplatesByIdsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTemplatesByIdsResp)
	err := c.cc.Invoke(ctx, TaskService_GetTemplatesByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetHttpServiceMappings(ctx context.Context, in *GetHttpServiceMappingsReq, opts ...grpc.CallOption) (*GetHttpServiceMappingsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHttpServiceMappingsResp)
	err := c.cc.Invoke(ctx, TaskService_GetHttpServiceMappings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetSubfinderProviders(ctx context.Context, in *GetSubfinderProvidersReq, opts ...grpc.CallOption) (*GetSubfinderProvidersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubfinderProvidersResp)
	err := c.cc.Invoke(ctx, TaskService_GetSubfinderProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
// All implementations must embed UnimplementedTaskServiceServer
// for forward compatibility.
//
// 任务服务
type TaskServiceServer interface {
	// 检查任务状态
	CheckTask(context.Context, *CheckTaskReq) (*CheckTaskResp, error)
	// 更新任务状态
	UpdateTask(context.Context, *UpdateTaskReq) (*UpdateTaskResp, error)
	// 创建执行器任务
	NewTask(context.Context, *NewTaskReq) (*NewTaskResp, error)
	// 保存任务结果
	SaveTaskResult(context.Context, *SaveTaskResultReq) (*SaveTaskResultResp, error)
	// 保存漏洞结果
	SaveVulResult(context.Context, *SaveVulResultReq) (*SaveVulResultResp, error)
	// Worker心跳
	KeepAlive(context.Context, *KeepAliveReq) (*KeepAliveResp, error)
	// 获取Worker配置
	GetWorkerConfig(context.Context, *GetWorkerConfigReq) (*GetWorkerConfigResp, error)
	// 请求资源文件
	RequestResource(context.Context, *RequestResourceReq) (*RequestResourceResp, error)
	// 根据标签获取模板
	GetTemplatesByTags(context.Context, *GetTemplatesByTagsReq) (*GetTemplatesByTagsResp, error)
	// 获取自定义指纹
	GetCustomFingerprints(context.Context, *GetCustomFingerprintsReq) (*GetCustomFingerprintsResp, error)
	// 验证指纹匹配
	ValidateFingerprint(context.Context, *ValidateFingerprintReq) (*ValidateFingerprintResp, error)
	// POC验证
	ValidatePoc(context.Context, *ValidatePocReq) (*ValidatePocResp, error)
	// 批量POC验证
	BatchValidatePoc(context.Context, *BatchValidatePocReq) (*BatchValidatePocResp, error)
	// 查询POC验证结果
	GetPocValidationResult(context.Context, *GetPocValidationResultReq) (*GetPocValidationResultResp, error)
	// 根据ID获取POC内容
	GetPocById(context.Context, *GetPocByIdReq) (*GetPocByIdResp, error)
	// 根据ID列表批量获取模板内容
	GetTemplatesByIds(context.Context, *GetTemplatesByIdsReq) (*GetTemplatesByIdsResp, error)
	// 获取HTTP服务映射
	GetHttpServiceMappings(context.Context, *GetHttpServiceMappingsReq) (*GetHttpServiceMappingsResp, error)
	// 获取Subfinder数据源配置
	GetSubfinderProviders(context.Context, *GetSubfinderProvidersReq) (*GetSubfinderProvidersResp, error)
	mustEmbedUnimplementedTaskServiceServer()
}

// UnimplementedTaskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskServiceServer struct{}

func (UnimplementedTaskServiceServer) CheckTask(context.Context, *CheckTaskReq) (*CheckTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckTask not implemented")
}
func (UnimplementedTaskServiceServer) UpdateTask(context.Context, *UpdateTaskReq) (*UpdateTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTask not implemented")
}
func (UnimplementedTaskServiceServer) NewTask(context.Context, *NewTaskReq) (*NewTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method NewTask not implemented")
}
func (UnimplementedTaskServiceServer) SaveTaskResult(context.Context, *SaveTaskResultReq) (*SaveTaskResultResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveTaskResult not implemented")
}
func (UnimplementedTaskServiceServer) SaveVulResult(context.Context, *SaveVulResultReq) (*SaveVulResultResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveVulResult not implemented")
}
func (UnimplementedTaskServiceServer) KeepAlive(context.Context, *KeepAliveReq) (*KeepAliveResp, error) {
	return nil, status.Error(codes.Unimplemented, "method KeepAlive not implemented")
}
func (UnimplementedTaskServiceServer) GetWorkerConfig(context.Context, *GetWorkerConfigReq) (*GetWorkerConfigResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkerConfig not implemented")
}
func (UnimplementedTaskServiceServer) RequestResource(context.Context, *RequestResourceReq) (*RequestResourceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestResource not implemented")
}
func (UnimplementedTaskServiceServer) GetTemplatesByTags(context.Context, *GetTemplatesByTagsReq) (*GetTemplatesByTagsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTemplatesByTags not implemented")
}
func (UnimplementedTaskServiceServer) GetCustomFingerprints(context.Context, *GetCustomFingerprintsReq) (*GetCustomFingerprintsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCustomFingerprints not implemented")
}
func (UnimplementedTaskServiceServer) ValidateFingerprint(context.Context, *ValidateFingerprintReq) (*ValidateFingerprintResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateFingerprint not implemented")
}
func (UnimplementedTaskServiceServer) ValidatePoc(context.Context, *ValidatePocReq) (*ValidatePocResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidatePoc not implemented")
}
func (UnimplementedTaskServiceServer) BatchValidatePoc(context.Context, *BatchValidatePocReq) (*BatchValidatePocResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchValidatePoc not implemented")
}
func (UnimplementedTaskServiceServer) GetPocValidationResult(context.Context, *GetPocValidationResultReq) (*GetPocValidationResultResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPocValidationResult not implemented")
}
func (UnimplementedTaskServiceServer) GetPocById(context.Context, *GetPocByIdReq) (*GetPocByIdResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPocById not implemented")
}
func (UnimplementedTaskServiceServer) GetTemplatesByIds(context.Context, *GetTemplatesByIdsReq) (*GetTemplatesByIdsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTemplatesByIds not implemented")
}
func (UnimplementedTaskServiceServer) GetHttpServiceMappings(context.Context, *GetHttpServiceMappingsReq) (*GetHttpServiceMappingsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHttpServiceMappings not implemented")
}
func (UnimplementedTaskServiceServer) GetSubfinderProviders(context.Context, *GetSubfinderProvidersReq) (*GetSubfinderProvidersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubfinderProviders not implemented")
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}
func (UnimplementedTaskServiceServer) testEmbeddedByValue()                     {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_CheckTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CheckTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CheckTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CheckTask(ctx, req.(*CheckTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_UpdateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).UpdateTask(ctx, req.(*UpdateTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_NewTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).NewTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_NewTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).NewTask(ctx, req.(*NewTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_SaveTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveTaskResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).SaveTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_SaveTaskResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).SaveTaskResult(ctx, req.(*SaveTaskResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_SaveVulResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveVulResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).SaveVulResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_SaveVulResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).SaveVulResult(ctx, req.(*SaveVulResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_KeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepAliveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).KeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_KeepAlive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).KeepAlive(ctx, req.(*KeepAliveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetWorkerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkerConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetWorkerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetWorkerConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetWorkerConfig(ctx, req.(*GetWorkerConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_RequestResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestResourceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).RequestResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_RequestResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).RequestResource(ctx, req.(*RequestResourceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTemplatesByTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplatesByTagsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTemplatesByTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTemplatesByTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTemplatesByTags(ctx, req.(*GetTemplatesByTagsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetCustomFingerprints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomFingerprintsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetCustomFingerprints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetCustomFingerprints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetCustomFingerprints(ctx, req.(*GetCustomFingerprintsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ValidateFingerprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateFingerprintReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ValidateFingerprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ValidateFingerprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ValidateFingerprint(ctx, req.(*ValidateFingerprintReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ValidatePoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidatePocReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ValidatePoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ValidatePoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ValidatePoc(ctx, req.(*ValidatePocReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_BatchValidatePoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchValidatePocReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).BatchValidatePoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_BatchValidatePoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).BatchValidatePoc(ctx, req.(*BatchValidatePocReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetPocValidationResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPocValidationResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetPocValidationResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetPocValidationResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetPocValidationResult(ctx, req.(*GetPocValidationResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetPocById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPocByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetPocById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetPocById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetPocById(ctx, req.(*GetPocByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTemplatesByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplatesByIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTemplatesByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTemplatesByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTemplatesByIds(ctx, req.(*GetTemplatesByIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetHttpServiceMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHttpServiceMappingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetHttpServiceMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetHttpServiceMappings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetHttpServiceMappings(ctx, req.(*GetHttpServiceMappingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetSubfinderProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubfinderProvidersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetSubfinderProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetSubfinderProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetSubfinderProviders(ctx, req.(*GetSubfinderProvidersReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "task.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckTask",
			Handler:    _TaskService_CheckTask_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _TaskService_UpdateTask_Handler,
		},
		{
			MethodName: "NewTask",
			Handler:    _TaskService_NewTask_Handler,
		},
		{
			MethodName: "SaveTaskResult",
			Handler:    _TaskService_SaveTaskResult_Handler,
		},
		{
			MethodName: "SaveVulResult",
			Handler:    _TaskService_SaveVulResult_Handler,
		},
		{
			MethodName: "KeepAlive",
			Handler:    _TaskService_KeepAlive_Handler,
		},
		{
			MethodName: "GetWorkerConfig",
			Handler:    _TaskService_GetWorkerConfig_Handler,
		},
		{
			MethodName: "RequestResource",
			Handler:    _TaskService_RequestResource_Handler,
		},
		{
			MethodName: "GetTemplatesByTags",
			Handler:    _TaskService_GetTemplatesByTags_Handler,
		},
		{
			MethodName: "GetCustomFingerprints",
			Handler:    _TaskService_GetCustomFingerprints_Handler,
		},
		{
			MethodName: "ValidateFingerprint",
			Handler:    _TaskService_ValidateFingerprint_Handler,
		},
		{
			MethodName: "ValidatePoc",
			Handler:    _TaskService_ValidatePoc_Handler,
		},
		{
			MethodName: "BatchValidatePoc",
			Handler:    _TaskService_BatchValidatePoc_Handler,
		},
		{
			MethodName: "GetPocValidationResult",
			Handler:    _TaskService_GetPocValidationResult_Handler,
		},
		{
			MethodName: "GetPocById",
			Handler:    _TaskService_GetPocById_Handler,
		},
		{
			MethodName: "GetTemplatesByIds",
			Handler:    _TaskService_GetTemplatesByIds_Handler,
		},
		{
			MethodName: "GetHttpServiceMappings",
			Handler:    _TaskService_GetHttpServiceMappings_Handler,
		},
		{
			MethodName: "GetSubfinderProviders",
			Handler:    _TaskService_GetSubfinderProviders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task.proto",
}
