// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: task.proto

package taskservice

import (
	"context"

	"cscan/rpc/task/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AssetDocument              = pb.AssetDocument
	BatchValidatePocReq        = pb.BatchValidatePocReq
	BatchValidatePocResp       = pb.BatchValidatePocResp
	CheckTaskReq               = pb.CheckTaskReq
	CheckTaskResp              = pb.CheckTaskResp
	FingerprintDocument        = pb.FingerprintDocument
	GetCustomFingerprintsReq   = pb.GetCustomFingerprintsReq
	GetCustomFingerprintsResp  = pb.GetCustomFingerprintsResp
	GetHttpServiceMappingsReq  = pb.GetHttpServiceMappingsReq
	GetHttpServiceMappingsResp = pb.GetHttpServiceMappingsResp
	GetPocByIdReq              = pb.GetPocByIdReq
	GetPocByIdResp             = pb.GetPocByIdResp
	GetPocValidationResultReq  = pb.GetPocValidationResultReq
	GetPocValidationResultResp = pb.GetPocValidationResultResp
	GetSubfinderProvidersReq   = pb.GetSubfinderProvidersReq
	GetSubfinderProvidersResp  = pb.GetSubfinderProvidersResp
	GetTemplatesByIdsReq       = pb.GetTemplatesByIdsReq
	GetTemplatesByIdsResp      = pb.GetTemplatesByIdsResp
	GetTemplatesByTagsReq      = pb.GetTemplatesByTagsReq
	GetTemplatesByTagsResp     = pb.GetTemplatesByTagsResp
	GetWorkerConfigReq         = pb.GetWorkerConfigReq
	GetWorkerConfigResp        = pb.GetWorkerConfigResp
	HttpServiceMappingDocument = pb.HttpServiceMappingDocument
	IPV4                       = pb.IPV4
	IPV6                       = pb.IPV6
	KeepAliveReq               = pb.KeepAliveReq
	KeepAliveResp              = pb.KeepAliveResp
	MatchedFingerprintInfo     = pb.MatchedFingerprintInfo
	NewTaskReq                 = pb.NewTaskReq
	NewTaskResp                = pb.NewTaskResp
	PocValidationResult        = pb.PocValidationResult
	RequestResourceReq         = pb.RequestResourceReq
	RequestResourceResp        = pb.RequestResourceResp
	SaveTaskResultReq          = pb.SaveTaskResultReq
	SaveTaskResultResp         = pb.SaveTaskResultResp
	SaveVulResultReq           = pb.SaveVulResultReq
	SaveVulResultResp          = pb.SaveVulResultResp
	SubfinderProviderDocument  = pb.SubfinderProviderDocument
	UpdateTaskReq              = pb.UpdateTaskReq
	UpdateTaskResp             = pb.UpdateTaskResp
	ValidateFingerprintReq     = pb.ValidateFingerprintReq
	ValidateFingerprintResp    = pb.ValidateFingerprintResp
	ValidatePocReq             = pb.ValidatePocReq
	ValidatePocResp            = pb.ValidatePocResp
	VulDocument                = pb.VulDocument

	TaskService interface {
		// 检查任务状态
		CheckTask(ctx context.Context, in *CheckTaskReq, opts ...grpc.CallOption) (*CheckTaskResp, error)
		// 更新任务状态
		UpdateTask(ctx context.Context, in *UpdateTaskReq, opts ...grpc.CallOption) (*UpdateTaskResp, error)
		// 创建执行器任务
		NewTask(ctx context.Context, in *NewTaskReq, opts ...grpc.CallOption) (*NewTaskResp, error)
		// 保存任务结果
		SaveTaskResult(ctx context.Context, in *SaveTaskResultReq, opts ...grpc.CallOption) (*SaveTaskResultResp, error)
		// 保存漏洞结果
		SaveVulResult(ctx context.Context, in *SaveVulResultReq, opts ...grpc.CallOption) (*SaveVulResultResp, error)
		// Worker心跳
		KeepAlive(ctx context.Context, in *KeepAliveReq, opts ...grpc.CallOption) (*KeepAliveResp, error)
		// 获取Worker配置
		GetWorkerConfig(ctx context.Context, in *GetWorkerConfigReq, opts ...grpc.CallOption) (*GetWorkerConfigResp, error)
		// 请求资源文件
		RequestResource(ctx context.Context, in *RequestResourceReq, opts ...grpc.CallOption) (*RequestResourceResp, error)
		// 根据标签获取模板
		GetTemplatesByTags(ctx context.Context, in *GetTemplatesByTagsReq, opts ...grpc.CallOption) (*GetTemplatesByTagsResp, error)
		// 获取自定义指纹
		GetCustomFingerprints(ctx context.Context, in *GetCustomFingerprintsReq, opts ...grpc.CallOption) (*GetCustomFingerprintsResp, error)
		// 验证指纹匹配
		ValidateFingerprint(ctx context.Context, in *ValidateFingerprintReq, opts ...grpc.CallOption) (*ValidateFingerprintResp, error)
		// POC验证
		ValidatePoc(ctx context.Context, in *ValidatePocReq, opts ...grpc.CallOption) (*ValidatePocResp, error)
		// 批量POC验证
		BatchValidatePoc(ctx context.Context, in *BatchValidatePocReq, opts ...grpc.CallOption) (*BatchValidatePocResp, error)
		// 查询POC验证结果
		GetPocValidationResult(ctx context.Context, in *GetPocValidationResultReq, opts ...grpc.CallOption) (*GetPocValidationResultResp, error)
		// 根据ID获取POC内容
		GetPocById(ctx context.Context, in *GetPocByIdReq, opts ...grpc.CallOption) (*GetPocByIdResp, error)
		// 根据ID列表批量获取模板内容
		GetTemplatesByIds(ctx context.Context, in *GetTemplatesByIdsReq, opts ...grpc.CallOption) (*GetTemplatesByIdsResp, error)
		// 获取HTTP服务映射
		GetHttpServiceMappings(ctx context.Context, in *GetHttpServiceMappingsReq, opts ...grpc.CallOption) (*GetHttpServiceMappingsResp, error)
		// 获取Subfinder数据源配置
		GetSubfinderProviders(ctx context.Context, in *GetSubfinderProvidersReq, opts ...grpc.CallOption) (*GetSubfinderProvidersResp, error)
	}

	defaultTaskService struct {
		cli zrpc.Client
	}
)

func NewTaskService(cli zrpc.Client) TaskService {
	return &defaultTaskService{
		cli: cli,
	}
}

// 检查任务状态
func (m *defaultTaskService) CheckTask(ctx context.Context, in *CheckTaskReq, opts ...grpc.CallOption) (*CheckTaskResp, error) {
	client := pb.NewTaskServiceClient(m.cli.Conn())
	return client.CheckTask(ctx, in, opts...)
}

// 更新任务状态
func (m *defaultTaskService) UpdateTask(ctx context.Context, in *UpdateTaskReq, opts ...grpc.CallOption) (*UpdateTaskResp, error) {
	client := pb.NewTaskServiceClient(m.cli.Conn())
	return client.UpdateTask(ctx, in, opts...)
}

// 创建执行器任务
func (m *defaultTaskService) NewTask(ctx context.Context, in *NewTaskReq, opts ...grpc.CallOption) (*NewTaskResp, error) {
	client := pb.NewTaskServiceClient(m.cli.Conn())
	return client.NewTask(ctx, in, opts...)
}

// 保存任务结果
func (m *defaultTaskService) SaveTaskResult(ctx context.Context, in *SaveTaskResultReq, opts ...grpc.CallOption) (*SaveTaskResultResp, error) {
	client := pb.NewTaskServiceClient(m.cli.Conn())
	return client.SaveTaskResult(ctx, in, opts...)
}

// 保存漏洞结果
func (m *defaultTaskService) SaveVulResult(ctx context.Context, in *SaveVulResultReq, opts ...grpc.CallOption) (*SaveVulResultResp, error) {
	client := pb.NewTaskServiceClient(m.cli.Conn())
	return client.SaveVulResult(ctx, in, opts...)
}

// Worker心跳
func (m *defaultTaskService) KeepAlive(ctx context.Context, in *KeepAliveReq, opts ...grpc.CallOption) (*KeepAliveResp, error) {
	client := pb.NewTaskServiceClient(m.cli.Conn())
	return client.KeepAlive(ctx, in, opts...)
}

// 获取Worker配置
func (m *defaultTaskService) GetWorkerConfig(ctx context.Context, in *GetWorkerConfigReq, opts ...grpc.CallOption) (*GetWorkerConfigResp, error) {
	client := pb.NewTaskServiceClient(m.cli.Conn())
	return client.GetWorkerConfig(ctx, in, opts...)
}

// 请求资源文件
func (m *defaultTaskService) RequestResource(ctx context.Context, in *RequestResourceReq, opts ...grpc.CallOption) (*RequestResourceResp, error) {
	client := pb.NewTaskServiceClient(m.cli.Conn())
	return client.RequestResource(ctx, in, opts...)
}

// 根据标签获取模板
func (m *defaultTaskService) GetTemplatesByTags(ctx context.Context, in *GetTemplatesByTagsReq, opts ...grpc.CallOption) (*GetTemplatesByTagsResp, error) {
	client := pb.NewTaskServiceClient(m.cli.Conn())
	return client.GetTemplatesByTags(ctx, in, opts...)
}

// 获取自定义指纹
func (m *defaultTaskService) GetCustomFingerprints(ctx context.Context, in *GetCustomFingerprintsReq, opts ...grpc.CallOption) (*GetCustomFingerprintsResp, error) {
	client := pb.NewTaskServiceClient(m.cli.Conn())
	return client.GetCustomFingerprints(ctx, in, opts...)
}

// 验证指纹匹配
func (m *defaultTaskService) ValidateFingerprint(ctx context.Context, in *ValidateFingerprintReq, opts ...grpc.CallOption) (*ValidateFingerprintResp, error) {
	client := pb.NewTaskServiceClient(m.cli.Conn())
	return client.ValidateFingerprint(ctx, in, opts...)
}

// POC验证
func (m *defaultTaskService) ValidatePoc(ctx context.Context, in *ValidatePocReq, opts ...grpc.CallOption) (*ValidatePocResp, error) {
	client := pb.NewTaskServiceClient(m.cli.Conn())
	return client.ValidatePoc(ctx, in, opts...)
}

// 批量POC验证
func (m *defaultTaskService) BatchValidatePoc(ctx context.Context, in *BatchValidatePocReq, opts ...grpc.CallOption) (*BatchValidatePocResp, error) {
	client := pb.NewTaskServiceClient(m.cli.Conn())
	return client.BatchValidatePoc(ctx, in, opts...)
}

// 查询POC验证结果
func (m *defaultTaskService) GetPocValidationResult(ctx context.Context, in *GetPocValidationResultReq, opts ...grpc.CallOption) (*GetPocValidationResultResp, error) {
	client := pb.NewTaskServiceClient(m.cli.Conn())
	return client.GetPocValidationResult(ctx, in, opts...)
}

// 根据ID获取POC内容
func (m *defaultTaskService) GetPocById(ctx context.Context, in *GetPocByIdReq, opts ...grpc.CallOption) (*GetPocByIdResp, error) {
	client := pb.NewTaskServiceClient(m.cli.Conn())
	return client.GetPocById(ctx, in, opts...)
}

// 根据ID列表批量获取模板内容
func (m *defaultTaskService) GetTemplatesByIds(ctx context.Context, in *GetTemplatesByIdsReq, opts ...grpc.CallOption) (*GetTemplatesByIdsResp, error) {
	client := pb.NewTaskServiceClient(m.cli.Conn())
	return client.GetTemplatesByIds(ctx, in, opts...)
}

// 获取HTTP服务映射
func (m *defaultTaskService) GetHttpServiceMappings(ctx context.Context, in *GetHttpServiceMappingsReq, opts ...grpc.CallOption) (*GetHttpServiceMappingsResp, error) {
	client := pb.NewTaskServiceClient(m.cli.Conn())
	return client.GetHttpServiceMappings(ctx, in, opts...)
}

// 获取Subfinder数据源配置
func (m *defaultTaskService) GetSubfinderProviders(ctx context.Context, in *GetSubfinderProvidersReq, opts ...grpc.CallOption) (*GetSubfinderProvidersResp, error) {
	client := pb.NewTaskServiceClient(m.cli.Conn())
	return client.GetSubfinderProviders(ctx, in, opts...)
}
