// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: task.proto

package server

import (
	"context"

	"cscan/rpc/task/internal/logic"
	"cscan/rpc/task/internal/svc"
	"cscan/rpc/task/pb"
)

type TaskServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTaskServiceServer
}

func NewTaskServiceServer(svcCtx *svc.ServiceContext) *TaskServiceServer {
	return &TaskServiceServer{
		svcCtx: svcCtx,
	}
}

// 检查任务状态
func (s *TaskServiceServer) CheckTask(ctx context.Context, in *pb.CheckTaskReq) (*pb.CheckTaskResp, error) {
	l := logic.NewCheckTaskLogic(ctx, s.svcCtx)
	return l.CheckTask(in)
}

// 更新任务状态
func (s *TaskServiceServer) UpdateTask(ctx context.Context, in *pb.UpdateTaskReq) (*pb.UpdateTaskResp, error) {
	l := logic.NewUpdateTaskLogic(ctx, s.svcCtx)
	return l.UpdateTask(in)
}

// 创建执行器任务
func (s *TaskServiceServer) NewTask(ctx context.Context, in *pb.NewTaskReq) (*pb.NewTaskResp, error) {
	l := logic.NewNewTaskLogic(ctx, s.svcCtx)
	return l.NewTask(in)
}

// 保存任务结果
func (s *TaskServiceServer) SaveTaskResult(ctx context.Context, in *pb.SaveTaskResultReq) (*pb.SaveTaskResultResp, error) {
	l := logic.NewSaveTaskResultLogic(ctx, s.svcCtx)
	return l.SaveTaskResult(in)
}

// 保存漏洞结果
func (s *TaskServiceServer) SaveVulResult(ctx context.Context, in *pb.SaveVulResultReq) (*pb.SaveVulResultResp, error) {
	l := logic.NewSaveVulResultLogic(ctx, s.svcCtx)
	return l.SaveVulResult(in)
}

// Worker心跳
func (s *TaskServiceServer) KeepAlive(ctx context.Context, in *pb.KeepAliveReq) (*pb.KeepAliveResp, error) {
	l := logic.NewKeepAliveLogic(ctx, s.svcCtx)
	return l.KeepAlive(in)
}

// 获取Worker配置
func (s *TaskServiceServer) GetWorkerConfig(ctx context.Context, in *pb.GetWorkerConfigReq) (*pb.GetWorkerConfigResp, error) {
	l := logic.NewGetWorkerConfigLogic(ctx, s.svcCtx)
	return l.GetWorkerConfig(in)
}

// 请求资源文件
func (s *TaskServiceServer) RequestResource(ctx context.Context, in *pb.RequestResourceReq) (*pb.RequestResourceResp, error) {
	l := logic.NewRequestResourceLogic(ctx, s.svcCtx)
	return l.RequestResource(in)
}

// 根据标签获取模板
func (s *TaskServiceServer) GetTemplatesByTags(ctx context.Context, in *pb.GetTemplatesByTagsReq) (*pb.GetTemplatesByTagsResp, error) {
	l := logic.NewGetTemplatesByTagsLogic(ctx, s.svcCtx)
	return l.GetTemplatesByTags(in)
}

// 获取自定义指纹
func (s *TaskServiceServer) GetCustomFingerprints(ctx context.Context, in *pb.GetCustomFingerprintsReq) (*pb.GetCustomFingerprintsResp, error) {
	l := logic.NewGetCustomFingerprintsLogic(ctx, s.svcCtx)
	return l.GetCustomFingerprints(in)
}

// 验证指纹匹配
func (s *TaskServiceServer) ValidateFingerprint(ctx context.Context, in *pb.ValidateFingerprintReq) (*pb.ValidateFingerprintResp, error) {
	l := logic.NewValidateFingerprintLogic(ctx, s.svcCtx)
	return l.ValidateFingerprint(in)
}

// POC验证
func (s *TaskServiceServer) ValidatePoc(ctx context.Context, in *pb.ValidatePocReq) (*pb.ValidatePocResp, error) {
	l := logic.NewValidatePocLogic(ctx, s.svcCtx)
	return l.ValidatePoc(in)
}

// 批量POC验证
func (s *TaskServiceServer) BatchValidatePoc(ctx context.Context, in *pb.BatchValidatePocReq) (*pb.BatchValidatePocResp, error) {
	l := logic.NewBatchValidatePocLogic(ctx, s.svcCtx)
	return l.BatchValidatePoc(in)
}

// 查询POC验证结果
func (s *TaskServiceServer) GetPocValidationResult(ctx context.Context, in *pb.GetPocValidationResultReq) (*pb.GetPocValidationResultResp, error) {
	l := logic.NewGetPocValidationResultLogic(ctx, s.svcCtx)
	return l.GetPocValidationResult(in)
}

// 根据ID获取POC内容
func (s *TaskServiceServer) GetPocById(ctx context.Context, in *pb.GetPocByIdReq) (*pb.GetPocByIdResp, error) {
	l := logic.NewGetPocByIdLogic(ctx, s.svcCtx)
	return l.GetPocById(in)
}

// 根据ID列表批量获取模板内容
func (s *TaskServiceServer) GetTemplatesByIds(ctx context.Context, in *pb.GetTemplatesByIdsReq) (*pb.GetTemplatesByIdsResp, error) {
	l := logic.NewGetTemplatesByIdsLogic(ctx, s.svcCtx)
	return l.GetTemplatesByIds(in)
}

// 获取HTTP服务映射
func (s *TaskServiceServer) GetHttpServiceMappings(ctx context.Context, in *pb.GetHttpServiceMappingsReq) (*pb.GetHttpServiceMappingsResp, error) {
	l := logic.NewGetHttpServiceMappingsLogic(ctx, s.svcCtx)
	return l.GetHttpServiceMappings(in)
}

// 获取Subfinder数据源配置
func (s *TaskServiceServer) GetSubfinderProviders(ctx context.Context, in *pb.GetSubfinderProvidersReq) (*pb.GetSubfinderProvidersResp, error) {
	l := logic.NewGetSubfinderProvidersLogic(ctx, s.svcCtx)
	return l.GetSubfinderProviders(in)
}
